# Generated by Django 5.2.17 on 2026-09-04 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='password_hashed', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_age', models.IntegerField()),
                ('student_birthday', models.DateField()),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'student_profile',
                'managed': False,
            },
        ),
    ]
